Booking/ViewModels/PersonViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Booking.ViewModels
{
    public class PersonViewModel
    {
        [Display(Name = "Ім'я")]
        [Required(ErrorMessage = "Введіть ім'я.")]
        public string Name { get; set; }

        [Display(Name = "Прізвище")]
        [Required(ErrorMessage = "Введіть прізвище.")]
        public string Surname { get; set; }
        [Display(Name = "По батькові")]
        [Required(ErrorMessage = "Введіть по батькові.")]
        public string Patronymic { get; set; }

        [Display(Name = "Дата народження")]
        [Required(ErrorMessage = "Введіть дату народження.")]
        [DisplayFormat(DataFormatString = "{0:dd.mm.yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? DateOfBirth { get; set; }

        [EmailAddress]
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Введіть Email.")]
        public string Email { get; set; }

        [Phone]
        [Display(Name = "Телефон")]
        [Required(ErrorMessage = "Введіть номер телефону.")]
        public string Phone { get; set; }
    }
}

Booking/Controllers/PersonController.cs
using Booking.Interfaces.Mapping;
using Booking.ViewModels;
using Booking.WEB.BL.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Hosting;
using Booking.Interfaces;
using Booking.Models;
using System.Net;

namespace Booking.Controllers
{
    public class PersonController : Controller
    {
        private readonly IMapperControl mapperControl;
        private readonly IPersonService personService;
        private readonly IReservedSeatService reservedSeatService;
        private readonly IOrderService orderService;
        private readonly ITicketService ticketService;
        private readonly IPdfCreator pdfCreator;
        private readonly IEmailSender emailSender;

        private List<PersonViewModel> personViewModels;

        List<TicketViewModel> ticketViewModels;
        public PersonController( IMapperControl mapperControl, IPersonService personService,
            IReservedSeatService reservedSeatService, ITicketService ticketService,
            IOrderService orderService, IPdfCreator pdfCreator, IEmailSender emailSender)
        {
            this.mapperControl = mapperControl;
            this.personService = personService;
            this.reservedSeatService = reservedSeatService;
            this.ticketService = ticketService;
            this.orderService = orderService;
            this.pdfCreator = pdfCreator;
            this.emailSender = emailSender;
            personViewModels = new List<PersonViewModel>();
            ticketViewModels = new List<TicketViewModel>();
        }

        [HttpGet]
        public ActionResult PeopleForms()
        {
            RouteInfoViewModel model = Session["RouteInfo"] as RouteInfoViewModel;
            ViewBag.ChosenSeats = model.SelectedCarriage.ChosenSeats;
            
            for(int i = 0; i < model.SelectedCarriage.ChosenSeats.Count; i++)
            {
                personViewModels.Add(new PersonViewModel());
            }
            return View(personViewModels.ToList());
        }

        [HttpPost]
        public ActionResult PeopleForms(List<PersonViewModel> model)
        {
            var people = mapperControl.GetPersonListByPersonViewList(model);
            people = personService.CreatePerson(people);
           
            RouteInfoViewModel route = Session["RouteInfo"] as RouteInfoViewModel;
            List<ReservedSeatViewModel> seats = new List<ReservedSeatViewModel>();

            foreach(var el in route.SelectedCarriage.ChosenSeats)
            {
                seats.Add(new ReservedSeatViewModel { Number = el.Number, CarriageId = route.SelectedCarriage.CarriageId });
            }

            var reservedSeats = mapperControl.GetReservedSeatsByViewModel(seats);
            reservedSeats = reservedSeatService.Create(reservedSeats);

            for(int i = 0; i < people.Count(); i++)
            {
                int seatId = reservedSeats.Find(x => x.Number.Equals(route.SelectedCarriage.ChosenSeats[i].Number)).SeatId;
                ticketViewModels.Add(new TicketViewModel
                {
                    Email = people[i].Email,
                    TrainName = route.TrainName,
                    SeatNumber = route.SelectedCarriage.ChosenSeats[i].Number,
                    Price = route.SelectedCarriage.ChosenSeats[i].Price,
                    RouteId = route.RouteId,
                    Description = route.Description,
                    ArrivalTime = route.ArrivalTime,
                    CarriageNumber = route.SelectedCarriage.Number,
                    DepartureTime = route.DepartureTime,
                    SeatId = seatId,
                    SNP = String.Format("{0} {1} {2}", people[i].Name, people[i].Surname, people[i].Patronymic)
                });
            }
            var tickets = mapperControl.GetTicketsByViewModel(ticketViewModels);
            tickets = ticketService.Create(tickets);

            for(int i = 0; i < tickets.Count();i++)
            {
                orderService.MakeOrder(people[i].PersonId, tickets[i].TicketId);
            }

            CreatePdf(ticketViewModels);

            return View("GetTickets", ticketViewModels);
        }

       private void CreatePdf(List<TicketViewModel> ticketInfo)
        {
            pdfCreator.CreatePdf(ticketInfo);
        }

        public FileResult Download(int id)
        {
            string fileName = String.Format("ticket{0}.pdf", id);
            string filepath = String.Format(HostingEnvironment.MapPath("/App_Data/ticket{0}.pdf"), id);
            byte[] fileBytes = System.IO.File.ReadAllBytes(filepath);
            return File(fileBytes, "application/pdf", fileName);
        }

        public string EmailSender(int id, string email)
        {
            string filepath = String.Format(HostingEnvironment.MapPath("/App_Data/ticket{0}.pdf"), id);
            var emailAttachmentMessage = new EmailStringAttachment();
            emailAttachmentMessage.AttachmentsFilePath.Add(filepath);
            emailAttachmentMessage.Subject = "Білет";
            emailAttachmentMessage.Message = "Дякуємо, що разом з нами.\n Ваш Booking.";
            emailAttachmentMessage.EmailTo = email;
            string Result= string.Empty;
            var httpstatus=emailSender.SendEmail(emailAttachmentMessage);
            if (httpstatus.HttpStatusCode.Equals(HttpStatusCode.OK))
            {
                Result = "Повідомлення надіслано";
            }
            else
            {
                Result = "Проблеми з сервером. Скачайте білет";
            }

            return Result;
        }
    }
}

Booking/Views/Person/GetTickets.cshtml
@model IEnumerable<Booking.ViewModels.TicketViewModel>


@{
    ViewBag.Title = "GetTickets";

}

<script type="text/javascript">
   $(function(){
        $(".emailsender").click(function (e) {
            var url = this.href;
            var dialog = $("#dialog");
            if ($("#dialog").length == 0) {
                dialog = $('<div id="dialog" style="display:hidden"></div>').appendTo('body');
            }
            dialog.load(
                url,
                {}, 
                function (responseText, textStatus, XMLHttpRequest) {
                    dialog.dialog({                       
                        close: function (event, ui) {                            
                            dialog.remove();
                        },
                        modal: true,                            
                         width: 460, resizable: false
                    });
                }
            );           
            return false;           
        });
    });

</script>

<br />
<br />
<br />
<br />
<h2>Замовлені білети</h2>
<table class="table table-hover">
    <thead class="thead-style">
        <tr>
            <th>
                ФІО
            </th>
            <th>
                Маршрут
            </th>
            <th>
                Номер потяга
            </th>
            <th>
                Номер вагона
            </th>
            <th>
                Номер місця
            </th>
            <th>
                Час прибуття - <br />
                час відбуття
            </th>
            <th>
                Ціна
            </th>
            <th>

            </th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SNP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                №@Html.DisplayFor(modelItem => item.TrainName)
            </td>
            <td>
                №@Html.DisplayFor(modelItem => item.CarriageNumber)
            </td>
            <td>
                №@Html.DisplayFor(modelItem => item.SeatNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartureTime)-<br />
                @Html.DisplayFor(modelItem => item.ArrivalTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>

            <td>
                @Html.ActionLink("Скачати", "Download", new { id = item.SeatId }, new { @class = "btn btn-primary btn-lg btn-block fixedbuttonsize" }) <br />
                @Html.ActionLink("Скинути на почту", "EmailSender", new { id = item.SeatId, email = item.Email }, new { @class = "btn btn-primary btn-lg btn-block fixedbuttonsize emailsender " })
            </td>
        </tr>
    }

</table>

Booking/Views/Person/PeopleForms.cshtml
@model List<Booking.ViewModels.PersonViewModel>

@{
    ViewBag.Title = "PeopleForms";
    List<Booking.ViewModels.SelectedSeat> ChosenSeats = ViewBag.ChosenSeats;
}

<br />
<br />
<br />
<script src="@Url.Content("~/Scripts/user.validation.js")"></script>


@using (Html.BeginForm("PeopleForms", "Person", FormMethod.Post, new { @id = "personFormId" }))
{

    for (int i = 0; i < Model.Count(); i++)
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <h4>Місце пасажира - @ChosenSeats[i].Number.</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model[i].Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model[i].Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model[i].Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model[i].Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model[i].Surname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model[i].Surname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model[i].Patronymic, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model[i].Patronymic, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model[i].Patronymic, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model[i].DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model[i].DateOfBirth, new { htmlAttributes = new { @class = "form-control"} })
                    @Html.ValidationMessageFor(model => model[i].DateOfBirth, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model[i].Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model[i].Email, new { htmlAttributes = new { @class = "form-control"} })
                    @Html.ValidationMessageFor(model => model[i].Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model[i].Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model[i].Phone, new { htmlAttributes = new { @class = "form-control"} })
                    @Html.ValidationMessageFor(model => model[i].Phone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


    }
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Підтвердити бронювання" class="btn btn-primary btn-lg"  />
        </div>
    </div>

}